[backend]
# RPC host:port
host = '[::1]:18443'
# RPC cookie path
# cookie = '~/.bitcoin/regtest/.cookie'
# RPC user/pass
# rpcauth = ''
# whether to use the btcd websocket interface
websocket = false
# how quickly to poll for block updates, in milliseconds
# ignored if websocket is used
poll_interval = 500

[pogolo]
# takes precedence over ip, will listen on all interface ips
interface = 'lo'
# ipv4, v6, or domain (domain will only resolve the first ip)
# ip = '[::1]'
# use 0 to pick a random port
port = 5661
# port for the api
http_port = 5662
# optional, required for clients if set
# password = ''
# will be replaced by default tag if too long (see coinbase scriptsig limit)
tag = '/pogolo - foss is freedom/'
# minimum 0.01
default_difficulty = 1024.0
# how often to send new work to clients, in seconds
job_interval = 60
# how often we want shares on average, in seconds
target_share_interval = 10
# how often we should check to adjust a clients difficulty, in seconds
difficulty_adjustment_interval = 300
