[pogolo]
port = 5661
# takes precedence over ip, will listen on all interface ips
interface = "lo"
# ipv4, v6, or domain (domain will only resolve the first ip)
ip = "[::1]"
# optional, required for clients if set
#password = "x"
# will be replaced by default tag if too long (see coinbase scriptsig limit)
tag = "/pogolo - foss is freedom/"
# minimum 0.01
default_difficulty = 1024
# how often to send new work to clients, in seconds
job_interval = 60
# how often we want shares on average, in seconds
target_share_interval = 10

[backend]
host = "[::1]:8332"
cookie = "~/.bitcoin/.cookie"
# optional, rpc user/pass
#rpcauth = "pogolo:hash"
# how quickly to poll for block updates, in milliseconds
poll_interval = 500
