[pogolo]
# takes precedence over ip, will listen on all interface ips
interface = "wlan0"
# ipv4 or v6
ip = "[::1]"
port = 5661
# optional, required for clients if set
#password = "x"
# will be replaced by default tag if too long (see coinbase scriptsig limit)
tag = "/pogolo - foss is freedom/"
# minimum 0.16
default_difficulty = 1024

[backend]
host = "[::1]:8332"
cookie = "~/.bitcoin/rpc.cookie"
# optional, rpc user/pass
#rpcauth = "pogolo:hash"
# mainnet | testnet | regtest
chain = "regtest"
